export type Frame = {
  text: string;
  fontClass: string;
  sizeClass: string;
  weightClass?: string;
  colorClass: string;
  bgClass: string;
  trackingClass?: string;
  transformClass?: string;
  alignClass?: string;
  paddingClass?: string;
  rotateDeg?: number;
  italic?: boolean;
  underline?: boolean;
  strokeOnly?: boolean;
  blendDifference?: boolean;
  durationMs: number;
};

export const FRAMES: Frame[] = [
  {
    text: "LOREM",
    fontClass: "font-bebas",
    sizeClass: "text-[22vw]",
    colorClass: "text-yellow-300",
    bgClass: "bg-black",
    trackingClass: "tracking-tight",
    transformClass: "uppercase",
    durationMs: 320,
  },
  {
    text: "ipsum",
    fontClass: "font-caveat",
    sizeClass: "text-[18vw]",
    weightClass: "font-bold",
    colorClass: "text-black",
    bgClass: "bg-white",
    transformClass: "lowercase",
    alignClass: "items-start justify-start",
    paddingClass: "p-12",
    rotateDeg: -8,
    italic: true,
    durationMs: 180,
  },
  {
    text: "AD",
    fontClass: "font-anton",
    sizeClass: "text-[40vw]",
    colorClass: "text-white",
    bgClass: "bg-red-600",
    trackingClass: "tracking-tighter",
    transformClass: "uppercase",
    durationMs: 140,
  },
  {
    text: "sit",
    fontClass: "font-playfair",
    sizeClass: "text-[14vw]",
    weightClass: "font-black",
    colorClass: "text-red-600",
    bgClass: "bg-yellow-300",
    transformClass: "lowercase",
    alignClass: "items-end justify-end",
    paddingClass: "p-16",
    italic: true,
    durationMs: 200,
  },
  {
    text: "A M E T",
    fontClass: "font-major-mono",
    sizeClass: "text-[6vw]",
    colorClass: "text-lime-400",
    bgClass: "bg-black",
    trackingClass: "tracking-[0.4em]",
    transformClass: "uppercase",
    durationMs: 260,
  },
  {
    text: "...",
    fontClass: "font-bungee",
    sizeClass: "text-[30vw]",
    colorClass: "text-black",
    bgClass: "bg-lime-400",
    rotateDeg: 12,
    durationMs: 130,
  },
  {
    text: "consectetur",
    fontClass: "font-playfair",
    sizeClass: "text-3xl",
    weightClass: "font-light",
    colorClass: "text-white",
    bgClass: "bg-black",
    transformClass: "lowercase",
    italic: true,
    trackingClass: "tracking-widest",
    durationMs: 700,
  },
  {
    text: "ADIPISCING",
    fontClass: "font-anton",
    sizeClass: "text-[18vw]",
    colorClass: "text-white",
    bgClass: "bg-blue-700",
    transformClass: "uppercase",
    trackingClass: "tracking-tight",
    durationMs: 220,
  },
  {
    text: "&",
    fontClass: "font-playfair",
    sizeClass: "text-[50vw]",
    weightClass: "font-black",
    colorClass: "text-white",
    bgClass: "bg-black",
    italic: true,
    durationMs: 150,
  },
  {
    text: "ELIT",
    fontClass: "font-bungee",
    sizeClass: "text-[14vw]",
    colorClass: "text-yellow-300",
    bgClass: "bg-red-600",
    transformClass: "uppercase",
    durationMs: 220,
  },
  {
    text: "sed do eiusmod tempor",
    fontClass: "font-inter",
    sizeClass: "text-2xl",
    weightClass: "font-thin",
    colorClass: "text-white",
    bgClass: "bg-black",
    transformClass: "lowercase",
    trackingClass: "tracking-[0.3em]",
    alignClass: "items-end justify-start",
    paddingClass: "p-10",
    durationMs: 540,
  },
  {
    text: "LABORE",
    fontClass: "font-bebas",
    sizeClass: "text-[28vw]",
    colorClass: "text-black",
    bgClass: "bg-white",
    rotateDeg: -4,
    durationMs: 160,
  },
  {
    text: "UT",
    fontClass: "font-anton",
    sizeClass: "text-[35vw]",
    colorClass: "text-white",
    bgClass: "bg-black",
    transformClass: "uppercase",
    rotateDeg: 6,
    durationMs: 160,
  },
  {
    text: "E T",
    fontClass: "font-space-mono",
    sizeClass: "text-[12vw]",
    weightClass: "font-bold",
    colorClass: "text-black",
    bgClass: "bg-yellow-300",
    trackingClass: "tracking-[0.6em]",
    transformClass: "uppercase",
    durationMs: 200,
  },
  {
    text: "dolore.",
    fontClass: "font-caveat",
    sizeClass: "text-[20vw]",
    weightClass: "font-bold",
    colorClass: "text-pink-400",
    bgClass: "bg-black",
    rotateDeg: -10,
    durationMs: 260,
  },
  {
    text: "↓",
    fontClass: "font-inter",
    sizeClass: "text-[40vw]",
    weightClass: "font-black",
    colorClass: "text-black",
    bgClass: "bg-lime-400",
    alignClass: "items-start justify-end",
    paddingClass: "p-8",
    durationMs: 130,
  },
  {
    text: "magna aliqua",
    fontClass: "font-playfair",
    sizeClass: "text-4xl",
    weightClass: "font-extralight",
    colorClass: "text-white",
    bgClass: "bg-black",
    transformClass: "lowercase",
    italic: true,
    trackingClass: "tracking-widest",
    durationMs: 600,
  },
  {
    text: "VENIAM",
    fontClass: "font-bebas",
    sizeClass: "text-[12vw]",
    colorClass: "text-white",
    bgClass: "bg-black",
    transformClass: "uppercase",
    trackingClass: "tracking-[0.5em]",
    durationMs: 220,
  },
  {
    text: "quis nostrud exercitation",
    fontClass: "font-major-mono",
    sizeClass: "text-3xl",
    colorClass: "text-yellow-300",
    bgClass: "bg-blue-700",
    transformClass: "lowercase",
    alignClass: "items-end justify-end",
    paddingClass: "p-12",
    durationMs: 520,
  },
  {
    text: "NISI",
    fontClass: "font-bungee",
    sizeClass: "text-[22vw]",
    colorClass: "text-white",
    bgClass: "bg-red-600",
    rotateDeg: 90,
    durationMs: 180,
  },
  {
    text: "ALIQUIP",
    fontClass: "font-anton",
    sizeClass: "text-[18vw]",
    colorClass: "text-yellow-300",
    bgClass: "bg-black",
    transformClass: "uppercase",
    strokeOnly: true,
    durationMs: 220,
  },
  {
    text: "ex ea",
    fontClass: "font-caveat",
    sizeClass: "text-[26vw]",
    weightClass: "font-bold",
    colorClass: "text-white",
    bgClass: "bg-pink-400",
    alignClass: "items-start justify-start",
    paddingClass: "p-10",
    rotateDeg: -14,
    italic: true,
    durationMs: 150,
  },
  {
    text: "•",
    fontClass: "font-inter",
    sizeClass: "text-[60vw]",
    weightClass: "font-black",
    colorClass: "text-red-600",
    bgClass: "bg-white",
    durationMs: 110,
  },
  {
    text: "COMMODO",
    fontClass: "font-bebas",
    sizeClass: "text-[10vw]",
    colorClass: "text-white",
    bgClass: "bg-black",
    transformClass: "uppercase",
    underline: true,
    trackingClass: "tracking-tight",
    durationMs: 240,
  },
  {
    text: "CONSEQUAT",
    fontClass: "font-bungee",
    sizeClass: "text-[28vw]",
    colorClass: "text-yellow-300",
    bgClass: "bg-black",
    transformClass: "uppercase",
    blendDifference: true,
    durationMs: 820,
  },
];
